[package]
name = "git_toprepo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
gix-config = "0.40.0"
bstr = "1.11.0"
chrono = { version = "0.4.39", features = ["serde"] }
clap = { version = "4.5.8", features = ["derive"] }
colored = "2.1.0"
enum_dispatch = "0.3.13"
git2 = "0.19.0"
itertools = "0.13.0"
lazycell = "1.3.0"
regex = "1.10.5"
serde = { version = "1.0.214", features = ["default", "derive"] }
serde_with = { version = "3.11.0", features = ["macros"] }
tempfile = "3.13.0"
toml = "0.8.19"
url = "2.5.2"
