name: Release to PyPi
on:
  push:
    tags:
      - '**'
jobs:
  build-and-test:
    # Use the callable build-and-test job to run the CI tests.
    uses: ./.github/workflows/build-and-test.yaml
  release-pypi:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    environment: release-pypi
    permissions:
      # Give permission to trusted publishing.
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install python poetry
        uses: abatilo/actions-poetry@v2
      - name: Build the distribution package
        run: ./release.sh
      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
